repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.9'
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
    - id: black
      language_version: python3
      args: ['-t','py310','-t','py311','-t','py312','-t','py313','-t','py314']
# Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.20.0'
    hooks:
    - id: mypy
      name: mypy
      additional_dependencies: [types-PyYAML==6.0.12.20240808, types-python-dateutil]
