name: catalog-manager-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - black
  - cftime
  - ecgtools
  - flake8
  - jsonschema
  - netcdf4==1.6.0
  - pip
  - pip:
    - git+https://github.com/intake/intake-esm@main
    - git+https://github.com/ACCESS-NRI/intake-dataframe-catalog@main
    - pytest
    - pytest-cov
    - pre-commit
