name: catalog-manager-dev
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.11
  - black
  - cftime
  - ecgtools
  - intake-dataframe-catalog>=0.1.0
  - intake-esm>=2023.4.20
  - jsonschema
  - netcdf4==1.6.0
  - pip
  - pip:
    - ruff
    - pre-commit
