jsonschema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    name:
      type: string
    model:
      type: string
    description:
      type: string
    realm:
      type: string
      enum:
      - aerosol
      - atmos
      - atmosChem
      - land
      - landIce
      - none
      - ocean
      - ocnBgchem
      - seaIce
      - unknown
    frequency:
      type: string
      oneOf:
      - pattern: ^fx$
      - pattern: ^subhr$
      - pattern: ^\d+hr$
      - pattern: ^\d+day$
      - pattern: ^\d+mon$
      - pattern: ^\d+yr$
      - pattern: ^\d+dec$
    variable:
      type: array
      items:
        type: string
  required:
  - name
  - model
  - description
  - realm
  - frequency
  - variable
  additionalProperties: false
name_column: name
yaml_column: yaml
translator_groupby_columns:
- model
- realm
- frequency
