builder: "AccessEsm15Builder"

translator: null # use DefaultTranslator

metadata:
  model: "ACCESS-ESM1-5"

subcatalog_dir: "/g/data/tm70/ds0092/projects/nri_intake_catalog/catalogs/access-esm1-5"

catalogs:

  # 55 TB
  PI_GWL_B2035:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2035"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2035" 
  PI-GWL-B2040:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2040"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2040"
  PI-GWL-B2045:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2045"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2045"
  PI-GWL-B2050:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2050"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2050"
  PI-GWL-B2055:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2055"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2055"
  PI-GWL-B2060:
    description: "Climate stabilization run at different global warming levels with zero C02 emissions and pre-industrial aerosols, branched from ACCESS-ESM1.5 SSP-EDC-585-13 in 2060"
    path:
      - "/g/data/p73/archive/non-CMIP/ACCESS-ESM1-5/PI-GWL-B2060"