builder: null

translator: CcamTranslator

sources: 

  - metadata_yaml: /g/data/xp65/admin/access-nri-intake-catalog/config/metadata_sources/rcm-ccam-hq89/metadata.yaml
    path:
      - /g/data/hq89/catalog/v2/esm/catalog.json
