builder: null

translator: "Cmip5Translator"

subcatalog_dir: null

subcatalogs:

  - path:
      - /g/data/hh5/public/apps/nci-intake-catalogue/esgf/cmip5/catalogue_latest.json
    metadata_yaml: /g/data/tm70/intake/metadata/cmip5_cms/metadata.yaml