builder: null

translator: "Cmip6Translator"

metadata: null

subcatalog_dir: null

catalogs:

  CMIP6_CMS:
    description: "CMIP6 datasets catalogued by CLEX-CMS"
    paths:
      - "/g/data/hh5/public/apps/nci-intake-catalogue/esgf/cmip6/catalogue_latest.json"
      
  CMIP6_NCI_fs38:
    description: "Australian CMIP6-era datasets catalogued by NCI"
    paths:
      - "/g/data/dk92/catalog/v2/esm/cmip6-fs38/catalog.json"

  # 947 TB
  CMIP6_NCI_oi10:
    description: "Replicated CMIP6-era datasets catalogued by NCI"
    paths:
      - "/g/data/dk92/catalog/v2/esm/cmip6-oi10/catalog.json"