builder: null

translator: Cmip6Translator

sources:

  - path:
      - /g/data/dk92/catalog/v2/esm/cmip6-fs38/catalog.json
    metadata_yaml: /g/data/tm70/intake/metadata/cmip6_fs38/metadata.yaml
    
  - path:
      - /g/data/dk92/catalog/v2/esm/cmip6-oi10/catalog.json
    metadata_yaml: /g/data/tm70/intake/metadata/cmip6_oi10/metadata.yaml