builder: null

translator: Cmip6Translator

sources:

  - metadata_yaml: /g/data/xp65/admin/intake/metadata/cmip6_fs38/metadata.yaml
    path:
      - /g/data/fs38/catalog/v2/esm/catalog.json
    
  - metadata_yaml: /g/data/xp65/admin/intake/metadata/cmip6_oi10/metadata.yaml
    path:
      - /g/data/oi10/catalog/v2/esm/catalog.json

  - metadata_yaml: /g/data/xp65/admin/intake/metadata/cmip6_ig45/metadata.yaml
    path:
    - /g/data/ig45/catalog/v2/esm/catalog.json 