builder: null

translator: Cmip5Translator

sources:

  - metadata_yaml: /g/data/xp65/admin/intake/metadata/cmip5_al33/metadata.yaml
    path:
      - /g/data/al33/catalog/v2/esm/catalog.json
    
  - metadata_yaml: /g/data/xp65/admin/intake/metadata/cmip5_rr3/metadata.yaml
    path:
      - /g/data/rr3/catalog/v2/esm/catalog.json
