builder: null

translator: CordexTranslator

sources:

  - metadata_yaml: /g/data/xp65/admin/access-nri-intake-catalog/config/metadata_sources/cordex-ig45/metadata.yaml
    path:
      - /g/data/ig45/catalog/v2/esm/catalog.json
