builder: null

translator: Era5Translator

sources:

  - metadata_yaml: /g/data/tm70/intake/metadata/erai/metadata.yaml
    path:
      - /g/data/hh5/public/apps/nci-intake-catalogue/erai/catalogue.json
