builder: null

translator: "EraiTranslator"

metadata: null

subcatalog_dir: null

catalogs:

  ERAI_CMS:
    description: "ECMWF ERA-Interim reanalysis at subdaily (3hr/6hr) frequencies catalogued by CLEX-CMS"
    path:
      - "/g/data/hh5/public/apps/nci-intake-catalogue/erai/catalogue.json"