builder: null

translator: EraiTranslator

subcatalog_dir: null

subcatalogs:

  - path:
      - /g/data/hh5/public/apps/nci-intake-catalogue/erai/catalogue.json
    metadata_yaml: /g/data/tm70/intake/metadata/erai/metadata.yaml