builder: null

translator: EsmValToolTranslator

sources:

  - metadata_yaml: /g/data/xp65/admin/intake/metadata/esgf-ref-qv56/metadata.yaml
    path:
      - /g/data/xp65/public/apps/access-nri-intake-catalog/ct11_tmpdir_catalog/catalog.json
