builder: Mom6Builder

translator: DefaultTranslator

sources:

  - metadata_yaml: /g/data/ik11/outputs/mom6-om4-025/OM4_025.JRA_RYF/metadata.yaml
    path:
    - /g/data/ik11/outputs/mom6-om4-025/OM4_025.JRA_RYF

  - metadata_yaml: /g/data/ik11/outputs/mom6-panan/panant-01-hycom1-v13/metadata.yaml
    path:
    - /g/data/ik11/outputs/mom6-panan/panant-01-hycom1-v13

  - metadata_yaml: /g/data/ik11/outputs/mom6-panan/panant-01-zstar-v13/metadata.yaml
    path:
    - /g/data/ik11/outputs/mom6-panan/panant-01-zstar-v13
