jsonschema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    path:
      type: string
    realm:
      enum:
      - aerosol
      - atmos
      - atmosChem
      - land
      - landIce
      - none
      - ocean
      - ocnBgchem
      - seaIce
      - unknown
    frequency:
      type: string
      pattern: ^fx$|^subhr$|^\d+hr$|^\d+day$|^\d+mon$|^\d+yr$|^\d+dec$
    variable:
      type: array
      items:
        type: string
    start_date:
      type: string
      pattern: ^\d\d\d\d-\d\d-\d\d,\s\d\d:\d\d:\d\d$
    end_date:
      type: string
      pattern: ^\d\d\d\d-\d\d-\d\d,\s\d\d:\d\d:\d\d$
  required:
  - path
  - realm
  - frequency
  - variable
  - start_date
  - end_date
path_column: path
variable_column: variable
