name: access-nri-intake-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python>=3.9.2 # see https://github.com/dask/distributed/issues/7956
  - cftime
  - ecgtools>=2022.10.07
  - fsspec<=2023.5.0 # see https://github.com/ncar-xdev/ecgtools/issues/160
  - intake-dataframe-catalog>=0.1.1
  - intake-esm>=2023.4.20
  - jsonschema
  - pooch
  - pre-commit
  - pytest
  - xarray
  - pip
  - pip:
    - codecov
    - pytest-cov
