name: cmip5_rr3
experiment_uuid: 473d0c44-ab66-458c-b32e-1e1774175853
description: Australian CMIP5-era datasets catalogued by NCI
long_description: >-
  All CMIP5-era Australian published data contained under the project rr3.
  All file versions present are in the listing. 
  Maintained By: NCI 
  Contact: help@nci.org.au 
  References: https://pcmdi.llnl.gov/mips/cmip5/
model:
- CMIP5
nominal_resolution:
-
version: 
contact: NCI
email: help@nci.org.au
created: 
reference: 
license: 
url: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f7448_2157_9857_1076
related_experiments:
- 
notes: 
keywords:
- cmip
