name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest

      - name: Test Python 3.10
        run: pixi run -e test-py310 test

      - name: Test Python 3.11
        run: pixi run -e test-py311 test

      - name: Test Python 3.12
        run: pixi run -e test-py312 test

      - name: Test Python 3.13
        run: pixi run -e test-py313 test