name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test-py310, test-py311, test-py312, test-py313]
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: prefix-dev/setup-pixi@v0.9.2
      with:
        environments: ${{ matrix.environment }}
        # frozen: true # This seems hacky?

    - name: Clean workspace
      run: |
        git clean -fdx
        git reset --hard HEAD

    - name: Update lockfile
      run: |
        pixi lock 

    - name: Run tests and generate coverage report
      run: |
        pixi run -e ${{ matrix.environment }} test-cov

    - name: Upload code coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.codecov_token }}
        files: ./coverage.xml
