name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test-py310, test-py311, test-py312, test-py313]
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        environments: ${{ matrix.environment }}
        frozen: true # This seems hacky?


    - name: Run tests and generate coverage report
      run: |
        pixi clean && pixi run -e ${{ matrix.environment }} test-cov

    - name: Upload code coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.codecov_token }}
        files: ./coverage.xml
