name: Update catalog on Gadi
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update catalog
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            cd ${{secrets.GADI_REPO_PATH}}
            export RELEASE=${{ github.event.inputs.release_version }}
            cd bin
            qsub -v version=${RELEASE} build_all.sh

            
