name: Pixi Lock Diff

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pixi.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  pixi-lock-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          sparse-checkout: |
            pyproject.toml
            pixi.lock
          sparse-checkout-cone-mode: false

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f #v0.10.0
        with:
          run-install: false

      - name: Install pixi extensions
        run: pixi global install pixi-diff==0.1.5 pixi-diff-to-markdown==0.3.9

      - name: Generate lock diff with base branch
        working-directory: ./
        run: |
          git show origin/${{ github.base_ref }}:pixi.lock > /tmp/base.lock
          pixi diff --before /tmp/base.lock --after pixi.lock \
            | pixi diff-to-markdown > /tmp/diff.md

      - name: Comment lock diff on PR
        uses: access-nri/actions/.github/actions/comment@main
        with:
          number: ${{ github.event.pull_request.number }}
          label: pixi-lock-diff
          message-file: /tmp/diff.md
